
#
# Average distance between spawn attempts for Repurposed Structures Pyramids.
# 1 for spawning in most chunks and 1001 for none.
[Pyramids]
	#Range: 1 ~ 1001
	badlandsPyramidAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidDarkForestAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidSnowyAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidIcyAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidJungleAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidMushroomAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidOceanAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidGiantTreeTaigaAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidFlowerForestAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	netherPyramidAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	pyramidEndAverageChunkDistance = 1001
