
#
# Average distance between spawn attempts for Repurposed Structures Witch Huts.
# 1 for spawning in most chunks and 1001 for no spawn.
[Wells]
	#Range: 1 ~ 1001
	witchHutsOakAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	witchHutsTaigaAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	witchHutsGiantTreeTaigaAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	witchHutsBirchAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	witchHutsDarkForestAverageChunkDistance = 48
